name: Linter

on: push

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v1
      
      - name: Super-Linter
        uses: github/super-linter@v3.15.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
